<hr>
<div class="asa_admin_donate">
	<h3 class="hndle"><span><strong class="red">Like this plugin?</strong></span></h3>
	<div class="inside">
		<p><strong>Want to help make it better? All donations are used to improve this plugin, so donate now!</strong></p>
		<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
			<input type="hidden" name="cmd" value="_s-xclick" />
			<input type="hidden" name="hosted_button_id" value="8RDJYGJSNF9LY" />
			<input type="image" name="submit" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" alt="PayPal - The safer, easier way to pay online!" />
			<img src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" alt="" width="1" height="1" border="0" />
		</form>
		<p>and you could:</p>
		<ul>
			<li><a href="http://wordpress.org/extend/plugins/app-store-assistant/">Rate the plugin 5★ on WordPress.org</a></li>
		</ul>
	</div>
</div>